using BuilderPattern.Interfaces;

namespace BuilderPattern.Directors;

/// <summary>
/// 指挥者类
/// </summary>
public class ReportDirector
{
    public void BuildAnnualReport(IReportBuilder builder)
    {
        builder.SetFormat("PDF")
            .SetTitle("Annual Report 2025")
            .SetContent("This is the annual report content.")
            .SetFooter("Generated by Builder Pattern");
    }

    public void BuildCustomReport(IReportBuilder builder, string title, string content)
    {
        builder.SetFormat("PDF")
            .SetTitle(title)
            .SetContent(content)
            .SetFooter($"Generated on {DateTime.Now:yyyy/MM/dd HH:mm:ss}");
    }
}